alias fp='flatpak'
alias gs='git status'
alias al='cat /home/lwb/.bashrc.d/aliases.sh'
alias gdm-on='sudo systemctl enable gdm --force'
alias gdm-off='sudo systemctl disable gdm --force'
alias sddm-on='sudo systemctl enable sddm --force'
alias sddm-off='sudo systemctl disable sddm --force'
alias zsh-on='chsh -s $(which zsh)'
alias bash-on='chsh -s $(which bash)'
alias lsd='lsd'
alias l='lsd --oneline'
alias la='lsd -a'
alias lla='lsd -la'
alias lt='lsd --tree --depth=3 --size=default --color=always --icon=always --human-readable --group-directories-first'
alias cl='clear'
alias help=tldr
alias bat='bat --theme ansi -n --color=always'
